### ISSUE TITLE
FAQ Q1 (authentication) not up to date anymore

### ISSUE THREAD

**Issue by tbfpartner** [Stirling-Tools/Stirling-Tools.github.io#22]
Just wanted to let you guys know...

The FAQ mentions, that there is no authentication mechanics implemented. This is not the case anymore ;)

[docs/FAQ.md](https://github.com/Stirling-Tools/Stirling-Tools.github.io/blob/4a31a8807858435fd2108479e23684c778f5afdf/docs/FAQ.md)
https://stirlingtools.com/docs/FAQ

**Comment by Frooodle** [comment]
thanks! fixed
